{% set name = "libenzyme" %}
{% set version = "0.0.34" %}
{% set build_number = 0 %}

# Needed for the linter even though it's specified in conda_build_config.yaml
{% set llvm_major_version = llvm_major_version or "12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EnzymeAD/Enzyme/archive/v{{ version }}.tar.gz
  sha256: b4268562105f491d96f9984c5e612360255197317064b5ca44a261ebed9f4d05

build:
  number: {{ build_number }}
  string: llvm{{ llvm_major_version }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  # Loadable modules are not supported by LLVM on Windows
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - llvmdev-addons-enabled 11.1.0
    - lit
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("12.4") }}  # [osx and x86_64]
  run_constrained:
    - llvmdev-addons-enabled

test:
  commands:
    - test -f $PREFIX/lib/LLVMEnzyme-{{ llvm_major_version }}${SHLIB_EXT}  # [unix]

about:
  home: https://enzyme.mit.edu/
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE
  summary: 'High-performance automatic differentiation of LLVM'
  description: |
    The Enzyme project is a tool that takes arbitrary existing code as
    LLVM IR and computes the derivative (and gradient) of that function.
    This allows developers to use Enzyme to automatically create gradients
    of their source code without much additional work.
  doc_url: https://enzyme.mit.edu/
  dev_url: https://github.com/EnzymeAD/Enzyme

extra:
  recipe-maintainers:
    - ludgerpaehler
    - wsmoses

