{% set name = "numba-enzyme-env" %}
{% set version = "0.56.4" %}
{% set build_number = 0 %}
{% set sha256 = "ab96b731fb9dee12b404b42b7c1fb82c119352648906a80526afa73658895b73" %}

package:
   name: {{ name|lower }}
   version: {{ version }}

source:
  url: https://github.com/numba/numba/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  string: np{{ NPY_VER }}py{{ PY_VER }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.misc.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}      # [not (armv6l or armv7l or aarch64)]
    - {{ compiler('cxx') }}    # [not (armv6l or armv7l or aarch64)]
  host:
    - python 3.9
    - numpy 1.19
    - setuptools
    - importlib_metadata       # [py<39]
    # On channel https://anaconda.org/ludgerpaehler/
    - enzyme-llvmlite  # needs to go to the current enzyme-llvmlite
  run:
    - python 3.9
    # NumPy 1.22.0, 1.22.1, 1.22.2 are all broken for ufuncs, see #7756
    - numpy 1.19
    - setuptools
    - importlib_metadata       # [py<39]
    # On channel https://anaconda.org/ludgerpaehler/
    - enzyme-llvmlite 0.0.48
  run_constrained:
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
    # 0.3.17 buggy on M1 silicon
    # https://github.com/xianyi/OpenBLAS/blob/v0.3.20/Changelog.txt#L118
    # https://github.com/numba/numba/issues/7822#issuecomment-1063229855
    # Exclude 0.3.20 too
    # https://github.com/numba/numba/issues/8096
    - libopenblas >=0.3.18, !=0.3.20     # [arm64]
    # scipy 1.0 or later
    - scipy >=1.0

about:
  home: https://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: A special version of Numba for the development of Numba-Enzyme
