llvm_major_version:
  - 12
 # error: 'shared_mutex' is unavailable: introduced in macOS 10.12
 MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
   - "12.4"                # [osx and x86_64]
 MACOSX_SDK_VERSION:        # [osx and x86_64]
   - "12.4"                # [osx and x86_64] 
